media:
  input: src/media
  output: /media
content:
  - name: pages
    label: Pages
    path: src/pages
    type: collection
    fields:
      - name: title
        label: Title
        type: string
        required: true
  - name: blog
    label: Blog
    path: src/blog
    type: collection
    fields:
      - name: title
        label: Title
        type: string
        required: true